# Generated by Django 4.2.5 on 2024-01-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('smartphone', 'Smartphone'), ('smartwatch', 'Smartwatch'), ('glasses', 'Glasses')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('last_connected', models.DateTimeField()),
            ],
        ),
    ]
